### ISSUE TITLE
Different QQ-plot interfaces for Normal Distribution lab

### ISSUE THREAD

**Issue by rudeboybert** [beanumber/oiLabs-mosaic#20]
In [Evaluating the normal distribution](https://github.com/beanumber/oiLabs-mosaic/blob/master/normal_distribution/normal_distribution.Rmd#evaluating-the-normal-distribution)

* When plotting the single QQ-plot, you use the lattice package interface
* When plotting the real data QQ-plot and 8 simulated QQ-plots, you use the ggplot2 interface.

Was this deliberate on your part? If not, I suggest using a consistent interface.

**Comment by beanumber** [comment]
You mean the bit about `qqnormsim`? 

It's not deliberate -- it's just the path of least resistance for playing well with the other version of the labs. Actually, I think that `oilabs` now imports `ggplot2`, so I don't think the `require(ggplot2)` is necessary.

**Comment by rudeboybert** [comment]
Yep, `qqnormsim` and `qqmath`.
